FROM php:8.1-fpm

RUN apt update -y ; apt install -y git \
    curl \
    unzip \
    nano \
    telnet \
    nginx
RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php

RUN HASH=`curl -sS https://composer.github.io/installer.sig`

RUN php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

RUN php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

RUN docker-php-ext-install sockets
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

COPY ./composer.json ./composer.json
RUN composer install

COPY . .

RUN chmod -R +x .

COPY ./composer.json ./composer.json

COPY .deploy/nginx.conf /etc/nginx/sites-enabled/default

RUN chmod +x startup.sh

CMD ["./startup.sh"]
