version: '3'

services:
    mysql:
      image: mysql:8
      container_name: mysql
      command: --init-file /config/schema.sql
      ports:
        - "13306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=qazQAZ12++
        - MYSQL_PASSWORD=qazQAZ12++
      volumes:
        - ./config:/config
      networks:
        - pony-network

    rabbitmq:
      image: rabbitmq:3.8-management
      container_name: rabbitmq
      hostname: rabbitmq
      environment:
        - RABBITMQ_VHOST="/"
        - RABBITMQ_USERNAME="rabbitmq"
        - RABBITMQ_PASSWORD="rabbitmq"
      ports:
        - '15672:5672'
      networks:
        - pony-network

    app:
      build:
        context: .
        dockerfile: app.Dockerfile
      container_name: application
      hostname: application
      ports:
        - "8000:80"
      networks:
        - pony-network

    sms_sender:
      build:
        context: .
        dockerfile: smsServices.Dockerfile
      container_name: sms_sender
      command:
        - /var/www/services/SmsSender.php
      entrypoint: php
      restart: always
      networks:
        - pony-network

    successful_sms_storage:
      build:
        context: .
        dockerfile: smsServices.Dockerfile
      container_name: successful_sms_storage
      command:
        - /var/www/services/SuccessfulSmsStorage.php
      entrypoint: php
      restart: always
      networks:
        - pony-network

    failed_sms_storage:
      build:
        context: .
        dockerfile: smsServices.Dockerfile
      container_name: failed_sms_storage
      command:
        - /var/www/services/FailedSmsStorage.php
      entrypoint: php
      restart: always
      networks:
        - pony-network

networks:
  pony-network:
    driver: bridge
